name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  mingw:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { msystem: MINGW64, project: 'mingw-gcc', bindir: 'win64_mingw-gcc' },
          { msystem: CLANG64, project: 'mingw-clang', bindir: 'win64_mingw-clang' },
        ]
    name: mingw-${{ matrix.msystem }}
    runs-on: windows-latest
    steps:
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
          fetch-depth: 0
      - run: cd bx && git checkout 198cd12 || cd ..
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Prepare
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: make
          pacboy: cc:p
      - name: Build
        shell: msys2 {0}
        run: |
          cd bgfx
          make shaderc -j$(nproc) AR=ar CC=cc CXX=c++ MINGW=$MINGW_PREFIX \
            CFLAGS="-O2 -ffunction-sections -fdata-sections -flto" \
            CXXFLAGS="-O2 -ffunction-sections -fdata-sections -flto -fno-rtti" \
            LDFLAGS="-Wl,--gc-sections -flto -static -static-libgcc -static-libstdc++ -s"
      - name: Rename and strip binary
        shell: msys2 {0}
        run: |
          cd bgfx/.build/${{ matrix.bindir }}/bin
          cp shadercRelease.exe shaderc.exe
          strip --strip-all shaderc.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaderc-win-x64-${{ matrix.project }}.exe
          path: ./bgfx/.build/${{ matrix.bindir }}/bin/shaderc.exe
      - name: Zip binary
        run: Compress-Archive -Path ./bgfx/.build/${{ matrix.bindir }}/bin/shaderc.exe -Destination shaderc-win-x64-${{ matrix.project }}.zip
      - name: Publish binary
        uses: softprops/action-gh-release@v2
        with:
          files: shaderc-win-x64-${{ matrix.project }}.zip
          tag_name: binaries
          fail_on_unmatched_files: true

  linux:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { config: release, binsuffix: Release },
        ]
    name: linux-${{ matrix.config }}64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
          fetch-depth: 0
      - run: cd bx && git checkout 198cd12 || cd ..
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Build
        run: |
          sudo apt install libgl-dev
          cd bgfx
          make -j$(nproc) shaderc \
            CFLAGS="-O2 -ffunction-sections -fdata-sections -flto" \
            CXXFLAGS="-O2 -ffunction-sections -fdata-sections -flto -fno-rtti" \
            LDFLAGS="-Wl,--gc-sections -flto -s"
      - name: Rename and strip binary
        run: |
          cd bgfx/.build/linux64_gcc/bin
          cp shaderc${{ matrix.binsuffix }} shaderc
          strip --strip-all shaderc
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaderc-linux-x64
          path: ./bgfx/.build/linux64_gcc/bin/shaderc
      - name: Zip binary
        run: zip -j shaderc-linux-x64.zip ./bgfx/.build/linux64_gcc/bin/shaderc
      - name: Publish binary
        uses: softprops/action-gh-release@v2
        with:
          files: shaderc-linux-x64.zip
          tag_name: binaries
          fail_on_unmatched_files: true

  osx:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { config: release, binsuffix: Release },
        ]
    name: osx-x64-${{ matrix.config }}
    runs-on: macos-latest
    steps:
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
          fetch-depth: 0
      - run: cd bx && git checkout 198cd12 || cd ..
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Build
        run: |
          cd bgfx
          make -j$(sysctl -n hw.physicalcpu) shaderc \
            CFLAGS="-O2 -ffunction-sections -fdata-sections -flto" \
            CXXFLAGS="-O2 -ffunction-sections -fdata-sections -flto -fno-rtti" \
            LDFLAGS="-Wl,-dead_strip -flto"
      - name: Rename and strip binary
        run: |
          cd bgfx/.build/osx-x64/bin
          cp shaderc${{ matrix.binsuffix }} shaderc
          strip -x shaderc
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaderc-osx-x64
          path: ./bgfx/.build/osx-x64/bin/shaderc
      - name: Zip binary
        run: zip -j shaderc-osx-x64.zip ./bgfx/.build/osx-x64/bin/shaderc
      - name: Publish binary
        uses: softprops/action-gh-release@v2
        with:
          files: shaderc-osx-x64.zip
          tag_name: binaries
          fail_on_unmatched_files: true

  android:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { platform: arm },
          { platform: arm64 },
        ]
    name: android-${{ matrix.platform }}
    runs-on: ubuntu-22.04
    steps:
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
          fetch-depth: 0
      - run: cd bx && git checkout 198cd12 || cd ..
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Build
        run: |
          sudo apt install libgl-dev
          ar -cr $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libpthread.a
          ar -cr $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/libpthread.a
          cd bgfx
          make .build/projects/gmake-android-${{ matrix.platform }}
          make -j$(nproc) -R -C .build/projects/gmake-android-${{ matrix.platform }} shaderc config=release \
            CFLAGS="-O2 -ffunction-sections -fdata-sections -flto" \
            CXXFLAGS="-O2 -ffunction-sections -fdata-sections -flto -fno-rtti" \
            LDFLAGS="-Wl,--gc-sections -flto -s"
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Rename and strip binary
        run: |
          cd bgfx/.build/android-${{ matrix.platform }}/bin
          cp libshadercRelease shaderc
          $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --strip-all shaderc
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Check
        run: |
          cd bgfx
          ls -lash ".build/android-${{ matrix.platform }}/bin"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shaderc-android-${{ matrix.platform }}
          path: ./bgfx/.build/android-${{ matrix.platform }}/bin/shaderc
      - name: Zip binary
        run: zip -j shaderc-android-${{ matrix.platform }}.zip ./bgfx/.build/android-${{ matrix.platform }}/bin/shaderc
      - name: Publish binary
        uses: softprops/action-gh-release@v2
        with:
          files: shaderc-android-${{ matrix.platform }}.zip
          tag_name: binaries
          fail_on_unmatched_files: true
